---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1  # ← غيّرها لو منطقتك مختلفة
filters:
  tag:Name: Jenkins-Instance
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - ip-address    # ← هذا هو المهم
